<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_On Hand Amount</name>
   <tag></tag>
   <elementGuidId>2884b152-a1b6-4bf8-aedf-5f223c5124d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCashierAmt_txtInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'txtCashierAmt$txtInput' and @type = 'text' and @id = 'txtCashierAmt_txtInput' and @ref_element = 'Object Repository/Menu/Branch Operation Supervisor/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCashierAmt_txtInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f88c23a8-d5d0-4099-ae4e-cfa2c0aa4011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCashierAmt$txtInput</value>
      <webElementGuid>60061cd5-828c-40f4-a34a-9ed4585397b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd3f08a6-27e6-4c2a-a220-005ea440a87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e5a4327-f4d3-42d3-a5bd-aca0907fb3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCashierAmt_txtInput</value>
      <webElementGuid>92e46cfb-8a91-48bd-aef3-0f3326e90b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>b4a02951-7aae-4de5-993d-0054f55ec01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('txtCashierAmt_txtInput','txtCashierAmt_hdnInput','txtCashierAmt_txtInputDummy');</value>
      <webElementGuid>f743a2fc-4152-459f-a48e-22dc878fa8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('txtCashierAmt_txtInput');</value>
      <webElementGuid>78920aaa-27ef-4082-95f1-7513aa342e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>554325c2-3696-41d7-84af-b3f4e8bbb68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCashierAmt_txtInput&quot;)</value>
      <webElementGuid>8691114b-a4a7-4c9a-8b77-48bf453cbce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>a70a260b-f73e-4cd9-95b1-8691d07e97de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCashierAmt_txtInput']</value>
      <webElementGuid>3f486564-d728-4805-8e15-60679afe3d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFormInfo']/table/tbody/tr[4]/td[2]/input[2]</value>
      <webElementGuid>a7bfec90-6773-47e0-a306-b60a4ccf84ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>78f7331c-13f8-4b76-8214-b6aad89ca9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCashierAmt$txtInput' and @type = 'text' and @id = 'txtCashierAmt_txtInput']</value>
      <webElementGuid>85dbfb40-cdb4-454c-a199-487b7d61985b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
