<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cashier Password</name>
   <tag></tag>
   <elementGuidId>f0aace34-61c4-4638-af7c-91eaaf43c9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCashierPassword']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'txtCashierPassword' and @type = 'password' and @id = 'txtCashierPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCashierPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e8f6401-08b0-43ce-a628-8c43d9e0d2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCashierPassword</value>
      <webElementGuid>a12c5ab2-7651-4767-8012-7569fa768cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b78b863d-af6a-41a2-9123-4cb6e771b6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCashierPassword</value>
      <webElementGuid>b4078f04-faaf-4d64-bae2-3143c4835a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>3fb89af8-faac-4e53-9e64-0a2f9550c858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCashierPassword&quot;)</value>
      <webElementGuid>8b65cc89-0914-4dd9-9ea7-ad48e189bc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>4b68fda4-4cb2-4031-821d-623ac4ab2a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCashierPassword']</value>
      <webElementGuid>f5487910-11b7-42e7-9425-f210e9e1d211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFormInfo']/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>e0ff8dc5-4563-47bd-82b7-8cb2ab0e1c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>a2be1507-b9d7-41e8-9e1d-6e26d82f17e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCashierPassword' and @type = 'password' and @id = 'txtCashierPassword']</value>
      <webElementGuid>19e3ad74-04fa-4ef3-988a-8579b5d72f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
