<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cashier Open</name>
   <tag></tag>
   <elementGuidId>115f6ee8-cefd-4e7e-866a-00048990d577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lbCashierOpen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lbCashierOpen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d02d1e3b-05d3-4417-9b60-b1cb8e74a456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbCashierOpen</value>
      <webElementGuid>82752b86-6476-49ea-ac69-c9d4a87fda54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>0511893e-7c7f-4081-a9a8-b71e12571e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lbCashierOpen&quot;, &quot;&quot;, true, &quot;vgOpen&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>8f42a329-792d-4eda-869a-3b0dfe2d0e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cashier Open</value>
      <webElementGuid>d00555f7-4094-4c2c-8a8e-89ad0b94cd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbCashierOpen&quot;)</value>
      <webElementGuid>31cb3d6b-8cee-48ad-b7b6-2dd7cdede724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, KEDOYA_mainPage</value>
      <webElementGuid>ca54ead6-73ca-4854-9f24-9b3a5919047a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lbCashierOpen']</value>
      <webElementGuid>f5fcd960-38e0-477a-9fbc-7bea722c7265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOpenCashier']/table/tbody/tr[3]/td[4]/a</value>
      <webElementGuid>63ce569b-a854-48d1-bc94-222a8cdc8b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cashier Open')]</value>
      <webElementGuid>760712b7-4bcc-495a-8ad2-385aad8e5e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Head Cashier Balance'])[1]/following::a[1]</value>
      <webElementGuid>6643e988-16be-40fc-b915-371889cb689d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>e2f0d23d-aa7c-457c-aef5-e82c0f06db74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[-]'])[2]/preceding::a[1]</value>
      <webElementGuid>0690b3f3-04d1-43dc-8734-fdf28ed7ca5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashier List'])[1]/preceding::a[2]</value>
      <webElementGuid>76c1e202-edd8-4b8c-bcaf-87442333da8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cashier Open']/parent::*</value>
      <webElementGuid>00b4d96f-2033-4145-9d34-a999153bea08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lbCashierOpen&quot;, &quot;&quot;, true, &quot;vgOpen&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>d53719c6-f230-4ad3-877a-c7272b5d5763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>e034a565-c9a6-4b22-9189-9291abb6e842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lbCashierOpen' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lbCashierOpen&quot;, &quot;&quot;, true, &quot;vgOpen&quot;, &quot;&quot;, false, true))' and (text() = 'Cashier Open' or . = 'Cashier Open')]</value>
      <webElementGuid>c54bb01d-cad1-4a23-898b-e63e8ce94a8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
