<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Opening Amount</name>
   <tag></tag>
   <elementGuidId>a8242397-6c6e-4f24-95c5-a459d4b2707d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucOpeningAmount_txtInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ucOpeningAmount$txtInput' and @type = 'text' and @id = 'ucOpeningAmount_txtInput' and @ref_element = 'Object Repository/Menu/Branch Operation Supervisor/OpenCloseCashier/Page_New Confins - Main/iframe_Welcome, Djunaidy, KEDOYA_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucOpeningAmount_txtInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54e9422e-4a23-4251-adce-5e2a63d61802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucOpeningAmount$txtInput</value>
      <webElementGuid>afb35869-35a8-4412-a75e-a49a59adbca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a058dae-9275-4e7d-a70d-4bcf571293ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucOpeningAmount_txtInput</value>
      <webElementGuid>9223820b-27d2-4ec7-bb32-5af625c04a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>142c4b2b-5dc7-465b-853c-e28a84c07ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucOpeningAmount_txtInput','ucOpeningAmount_hdnInput','ucOpeningAmount_txtInputDummy');</value>
      <webElementGuid>a413014b-6f67-413e-a451-22fedc5efe97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucOpeningAmount_txtInput');</value>
      <webElementGuid>4d7406f2-c4db-470e-bca6-472c4b811009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>7bc6d89e-8d67-46fb-9375-e9f6f1090b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucOpeningAmount_txtInput&quot;)</value>
      <webElementGuid>6e5c9ed1-4b92-45d7-8532-57852e0177ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>078bb463-1d80-4bb4-b62f-c3d4422df496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucOpeningAmount_txtInput']</value>
      <webElementGuid>e84a1f80-0e41-4f7c-b2a8-77fd8cc61b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOpenCashier']/table/tbody/tr/td[4]/input[2]</value>
      <webElementGuid>5a58c498-24bb-4a01-b8f2-0e135ea272a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[2]</value>
      <webElementGuid>10d69bae-7343-4af1-b1dc-f908796daaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucOpeningAmount$txtInput' and @type = 'text' and @id = 'ucOpeningAmount_txtInput']</value>
      <webElementGuid>3f19a437-5c2b-48c5-9715-dab7b114ab4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
