<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CashierPassword</name>
   <tag></tag>
   <elementGuidId>34cb04e1-9b47-40b5-8548-9937632606c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCashierPassword']&#xd;
&#xd;
//*[@id=&quot;txtCashierPassword&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='txtCashierPassword'][count(. | //*[@id = 'txtCashierPassword' and @ref_element = 'Object Repository/Menu/Branch Operation Supervisor/OpenCloseCashier/Page_New Confins - Main/iframe_Welcome, Djunaidy, KEDOYA_mainPage']) = count(//*[@id = 'txtCashierPassword' and @ref_element = 'Object Repository/Menu/Branch Operation Supervisor/OpenCloseCashier/Page_New Confins - Main/iframe_Welcome, Djunaidy, KEDOYA_mainPage'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCashierPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>218639fb-b3fc-4bab-9303-02cadc23f563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCashierPassword</value>
      <webElementGuid>2a97a893-aaea-436d-8413-cbdd32a4ae01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>21d677f2-8f2f-4af7-9ba2-96467d97802a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCashierPassword</value>
      <webElementGuid>020d70cd-d010-414b-b6d2-4dd2017382c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>802fee4b-32cf-49f5-95de-62db79c89f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='txtCashierPassword']</value>
      <webElementGuid>3ea5432e-84a8-4110-998b-b98bc099dcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>534e4e36-1dd1-4469-b158-6fd58aed54f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCashierPassword']</value>
      <webElementGuid>5594caeb-b918-4a67-bf88-c3794a4a06db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOpenCashier']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1283b1d0-8078-40fc-b7c2-c660425d6213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>50ea9238-e563-4278-a143-5f7b5444bd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCashierPassword' and @type = 'password' and @id = 'txtCashierPassword']</value>
      <webElementGuid>94d9c9c8-9027-46f1-9a8c-901f3b52cf6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
