<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List status OpenClose</name>
   <tag></tag>
   <elementGuidId>62b69f5e-8f84-4577-b269-6c88628d5ef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlCashierStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlCashierStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ae2d592-1d5e-422a-80f4-1671da922705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlCashierStatus</value>
      <webElementGuid>dd7b4efd-89d8-4b3a-91c8-d2ebaac83814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlCashierStatus</value>
      <webElementGuid>af1ad9db-3f7a-4c2f-85ad-18f4a2e51df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddlMedStyle</value>
      <webElementGuid>66664cc8-87e6-4082-8f34-eb5c08a56db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Open
		Close

	</value>
      <webElementGuid>f6207e53-bb0f-449e-b761-3fd6221aadcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlCashierStatus&quot;)</value>
      <webElementGuid>211c64f1-c4aa-464b-bec5-ad21041bf9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/Page_New Confins - Main/iframe_Welcome, Djunaidy, KEDOYA_mainPage</value>
      <webElementGuid>c936fa54-d5a4-4deb-ab44-c1ca6f51ea3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlCashierStatus']</value>
      <webElementGuid>5ad4fede-d80a-4769-ba6f-32662db60495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dCashierHistGrid']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>8cfd739b-206b-480b-becc-d1ac53e3cb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashier Status'])[1]/following::select[1]</value>
      <webElementGuid>1a774766-7adf-4f32-926d-9c2ab9de8a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashier List'])[1]/following::select[1]</value>
      <webElementGuid>f196d88c-cf87-4955-901d-813fb6400c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[1]</value>
      <webElementGuid>c4d2cec7-0cc2-4caa-8c9c-6e268ed72d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Grid'])[1]/preceding::select[1]</value>
      <webElementGuid>221b6ee8-48d3-4c4d-8d40-4edc3d9464c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/table/tbody/tr/td[2]/select</value>
      <webElementGuid>15677248-0c04-45d8-b601-c5323ccbdd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlCashierStatus' and @id = 'ddlCashierStatus' and (text() = '
		Open
		Close

	' or . = '
		Open
		Close

	')]</value>
      <webElementGuid>4bac90d5-fd45-4392-b4ad-33e4f8efc8eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
