<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agreement No</name>
   <tag></tag>
   <elementGuidId>a7a8b8dd-3188-4eb0-afc2-21fe9ddc5a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fa1f046-4008-4c3d-aeb7-c4e1edeb917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtAgrmntNo_ltlAgrmntAgrmntNoSearch</value>
      <webElementGuid>ca3cc578-a2ee-480c-a279-f47f77b303b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b56d6ca-d7b1-43fd-9b4c-c875cd921bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch</value>
      <webElementGuid>41875c19-725f-4a06-a2e3-e59711fbbce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>8c27cb9e-7189-4bb4-9fab-a53aa6850bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch&quot;)</value>
      <webElementGuid>7e0748de-0a66-4fd6-b7b4-79bb5429bf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>848558d2-36b5-4839-937d-650d58346aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch']</value>
      <webElementGuid>65db3bbf-002e-4a3b-9a9c-06ee02f3508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr/td[4]/input</value>
      <webElementGuid>fceaff33-2ff3-4130-bc41-489f7358c009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>bb017b07-f86c-435c-8719-b12a37030dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucSearch$txtAgrmntNo_ltlAgrmntAgrmntNoSearch' and @type = 'text' and @id = 'ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch']</value>
      <webElementGuid>8312a81b-51a3-474d-9688-6ce6ab3e74b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
