<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference No</name>
   <tag></tag>
   <elementGuidId>7f4e34b3-0749-4cf7-86b9-d6a1981b3d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRefNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtRefNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd217a69-19df-4084-a0af-7c46e4cca0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtRefNo</value>
      <webElementGuid>fd3587e5-770b-4250-810f-1ec3f422fa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb6849a5-9794-4c1f-8b39-83c72f2ac318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>82c6fadf-86c2-45e7-b306-80e2f761372d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRefNo</value>
      <webElementGuid>ce49a5a1-2b88-4133-b0af-a1d540bbee64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRefNo&quot;)</value>
      <webElementGuid>ff9c85e5-8e7d-4ff0-a3f3-6bec060a8e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>195092d3-bf0f-4b3f-85a6-c5d17bc5aaa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRefNo']</value>
      <webElementGuid>f45696de-d4f3-48b6-8984-49efbbc632c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dGridOrg']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>326b0a6e-30b7-4ba2-beb0-e0f3b1bb1d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e17e35f3-0edd-4f25-91bd-f41dfc364c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtRefNo' and @type = 'text' and @id = 'txtRefNo']</value>
      <webElementGuid>b85bc1d8-9786-4708-a51c-b999ef0dfc57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
