<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notes_approval</name>
   <tag></tag>
   <elementGuidId>cb6feee3-6d6f-4b3b-80dd-f41609f824bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ucAppv_txtNotes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucAppv_txtNotes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>deecea9e-5e96-4515-abd4-07056623419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAppv$txtNotes</value>
      <webElementGuid>7f97e642-6839-45d1-a09c-0be1652a4773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>791fac0b-05e5-461a-b804-93cc62a6e43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f76066d4-9e44-4f42-b673-dd3f720e1ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAppv_txtNotes</value>
      <webElementGuid>b4a655d8-1dcb-4f7e-8c96-957337d60d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAppv_txtNotes&quot;)</value>
      <webElementGuid>7d100ddc-320d-41a1-9d0f-b6b5bb8b191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>e93a5b71-f330-4eb4-86b4-5e573261dc28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ucAppv_txtNotes']</value>
      <webElementGuid>abf2cfec-994c-40a2-aee9-2a1b74eae6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dApv']/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>6aa935c1-b08f-4eab-85c8-d4c5db5dadc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>5daaa104-7eaa-460d-9000-1104d55497f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ucAppv$txtNotes' and @id = 'ucAppv_txtNotes']</value>
      <webElementGuid>e10291bb-6b99-4ad2-84da-8fcb45e940b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
