<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OPEN_gvCashierHistctl02imbClose</name>
   <tag></tag>
   <elementGuidId>e2545d83-938d-485d-8bed-b5822882b1c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvCashierHist_imbClose_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvCashierHist_imbClose_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7e19c46-586a-45d2-a2ea-cd764c772123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>8c2bfcd3-c015-4916-864c-b6d10c4b5907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvCashierHist$ctl02$imbClose</value>
      <webElementGuid>62a569af-79a9-4ba4-8b9e-5070fcc4385a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvCashierHist_imbClose_0</value>
      <webElementGuid>52d3d28f-cef0-4163-81a6-e1b42b615dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close Cashier</value>
      <webElementGuid>d0073b1a-9158-49a4-9dee-54525521734a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Icon/IconDelete.gif</value>
      <webElementGuid>32ad31af-f20e-42c0-a235-c515dfef662a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvCashierHist_imbClose_0&quot;)</value>
      <webElementGuid>47c3e1aa-0965-44a6-a37d-c86115a47aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Close Cashier/Close baru/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>1b6758ab-3bbb-415a-82db-2b113fc612c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvCashierHist_imbClose_0']</value>
      <webElementGuid>ec9ef246-c018-4842-a9ae-b89d5de18523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvCashierHist']/tbody/tr[2]/td[8]/input</value>
      <webElementGuid>ef3badc5-edb2-44e6-a848-eadbffe371f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>b9b81461-0dd9-4bd8-b0f9-733ad1d05963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvCashierHist$ctl02$imbClose' and @id = 'gvCashierHist_imbClose_0' and @title = 'Close Cashier' and @src = '../../Images/Icon/IconDelete.gif']</value>
      <webElementGuid>61ddd480-d6b7-4bbd-9e26-0bb4120d1a8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
